<a href="https://colab.research.google.com/github/jarekwan/praca_inzynierska/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/ml_project')

from choose_source import choose_source
from load_data import load_data
from select_columns import select_columns_ui, select_columns
from detect_types import detect_types
from set_date import set_date_ui, set_date
import clean_data
import importlib
#import lib.reload(clean_data)
from clean_data import clean_data_ui, clean_data
from date_features import date_features_ui, date_features

Mounted at /content/drive
Mounted at /content/drive

In [ ]:
# step 1: ui for selecting the data source
choose_source()

VBox(children=(Dropdown(description='Format:', options=(('csv', 'csv'), ('json', 'json'), ('api', 'api')), val…

In [ ]:
# step 2: load the data into a dataframe
df = load_data()
print(df.head())

DataFrame saved to: /content/drive/MyDrive/ml_project/df.pkl
      PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0  PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1  PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2  PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3  PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4  PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials

  Order_Status  Quantity  Unit_Price  Negotiated_Price  Defective_Units  \
0    Cancelled      1176       20.13             17.81              NaN
1    Delivered      1509       39.32             37.34            235.0
2    Delivered       910       95.51             92.26             41.0
3    Delivered      1344       99.85             95.52            112.0
4    Delivered      1180       64.07             60.53            171.0

  Compliance
0        Yes
1        Yes
2        Yes
3        Yes
4         No

In [ ]:
# step 3: ui for selecting columns
select_columns_ui(df)

VBox(children=(Label(value='select columns for further analysis:'), Checkbox(value=False, description='PO_ID')…

In [ ]:
# step 4: apply the selected columns
df_selected = select_columns()
print(df_selected.head())

saved: /content/drive/MyDrive/ml_project/df_selected.pkl
selected columns: ['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category', 'Order_Status', 'Quantity', 'Unit_Price']
      PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0  PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1  PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2  PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3  PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4  PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials

  Order_Status  Quantity  Unit_Price
0    Cancelled      1176       20.13
1    Delivered      1509       39.32
2    Delivered       910       95.51
3    Delivered      1344       99.85
4    Delivered      1180       64.07

In [ ]:
# step 5 : detect the data types of all columns in df_selected.pkl
# this function loads the selected dataframe, identifies numerical,
# categorical and datetime columns, saves the result to column_types.csv,
# and returns a dictionary with the detected column groups
types_dict = detect_types()

# display the dictionary with column type groups
types_dict

saved: /content/drive/MyDrive/ml_project/column_types.csv
{'numerical': ['Quantity', 'Unit_Price'], 'categorical': ['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category', 'Order_Status'], 'datetime': []}

{'numerical': ['Quantity', 'Unit_Price'],
 'categorical': ['PO_ID',
  'Supplier',
  'Order_Date',
  'Delivery_Date',
  'Item_Category',
  'Order_Status'],
 'datetime': []}

In [ ]:
# step 6: show ui for selecting the date column and the fill method
# the function displays a widget where the user chooses:
# - which column contains dates
# - how missing values should be filled (zero, ffill, mean)
# the choices are saved to date_settings.txt

set_date_ui()

VBox(children=(Label(value='select the date column:'), Dropdown(options=('PO_ID', 'Supplier', 'Order_Date', 'D…

In [ ]:
# step 7: apply the date settings selected in the ui
# this function:
# - loads df_selected.pkl from drive
# - reads the date column and fill method from date_settings.txt
# - converts the date column to datetime
# - sorts the dataframe by date
# - fills missing values using the chosen method
# - saves the result as df_date.pkl
# - returns the processed dataframe for preview

df_date = set_date()
df_date.head()

saved: /content/drive/MyDrive/ml_project/df_date.pkl

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price
558,PO-00559,Alpha_Inc,2022-01-01,2022-01-07,Raw Materials,Delivered,1042,36.74
179,PO-00180,Alpha_Inc,2022-01-01,2022-01-12,Electronics,Delivered,552,21.52
521,PO-00522,Delta_Logistics,2022-01-02,2022-01-06,Packaging,Delivered,85,22.54
302,PO-00303,Alpha_Inc,2022-01-03,2022-01-20,Packaging,Delivered,172,63.61
420,PO-00421,Alpha_Inc,2022-01-04,2022-01-06,Electronics,Delivered,1004,50.70

In [ ]:
# step 8: ui that loads df_date.pkl from drive,
# counts missing values in the dataframe,
# shows the number of missing values,
# and lets the user choose how to handle them:
# drop, zero, ffill, mean or none.
from clean_data import clean_data_ui
clean_data_ui()

VBox(children=(Label(value='PO_ID: 0 missing'), Label(value='Supplier: 0 missing'), Label(value='Order_Date: 0…

In [ ]:
# step 9: applies the cleaning method selected in step 8.
# loads df_date.pkl and clean_method.txt from drive,
# performs: drop rows, fill with zero, forward fill,
# fill with mean or leave unchanged,
# then saves the result to df_clean.pkl.
df_clean = clean_data()
df_clean.head()

saved: /content/drive/MyDrive/ml_project/df_clean.pkl
applied per-column cleaning methods

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price
558,PO-00559,Alpha_Inc,2022-01-01,2022-01-07,Raw Materials,Delivered,1042,36.74
179,PO-00180,Alpha_Inc,2022-01-01,2022-01-12,Electronics,Delivered,552,21.52
521,PO-00522,Delta_Logistics,2022-01-02,2022-01-06,Packaging,Delivered,85,22.54
302,PO-00303,Alpha_Inc,2022-01-03,2022-01-20,Packaging,Delivered,172,63.61
420,PO-00421,Alpha_Inc,2022-01-04,2022-01-06,Electronics,Delivered,1004,50.70

In [ ]:
# step 10: date column selection for calendar features
date_features_ui()

In [ ]:
# step 11: generate calendar features
df_date_features = date_features()
df_date_features.head()