<a href="https://colab.research.google.com/github/jarekwan/praca_inzynierska/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.kill(os.getpid(), 9)

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
os.makedirs('/content/drive/MyDrive/ml_project', exist_ok=True)

import sys
sys.path.append('/content/drive/MyDrive/ml_project')



from choose_source import choose_source
from load_data import load_data
from select_columns import select_columns_ui, select_columns
from detect_types import detect_types
from set_date import set_date_ui, set_date
import clean_data
import importlib
#import lib.reload(clean_data)
from clean_data import clean_data_ui, clean_data
from date_features import date_features_ui, date_features
from create_lags import create_lags_ui, create_lags
from encode_categories import encode_categories_ui, encode_categories

Mounted at /content/drive
Mounted at /content/drive

In [2]:
# step 1: ui for selecting the data source
choose_source()

VBox(children=(Dropdown(description='Format:', options=(('csv', 'csv'), ('json', 'json'), ('api', 'api')), val…

In [3]:
# step 2: load the data into a dataframe
df = load_data()
print(df.head())

DataFrame saved to: /content/drive/MyDrive/ml_project/df.pkl
      PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0  PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1  PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2  PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3  PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4  PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials

  Order_Status  Quantity  Unit_Price  Negotiated_Price  Defective_Units  \
0    Cancelled      1176       20.13             17.81              NaN
1    Delivered      1509       39.32             37.34            235.0
2    Delivered       910       95.51             92.26             41.0
3    Delivered      1344       99.85             95.52            112.0
4    Delivered      1180       64.07             60.53            171.0

  Compliance
0        Yes
1        Yes
2        Yes
3        Yes
4         No

In [4]:
# step 3: ui for selecting columns
select_columns_ui(df)

VBox(children=(Label(value='select columns for further analysis:'), Checkbox(value=False, description='PO_ID')…

In [5]:
# step 4: apply the selected columns
df_selected = select_columns()
print(df_selected.head())

saved: /content/drive/MyDrive/ml_project/df_selected.pkl
selected columns: ['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category', 'Order_Status', 'Quantity', 'Unit_Price']
      PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0  PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1  PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2  PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3  PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4  PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials

  Order_Status  Quantity  Unit_Price
0    Cancelled      1176       20.13
1    Delivered      1509       39.32
2    Delivered       910       95.51
3    Delivered      1344       99.85
4    Delivered      1180       64.07

In [6]:
# step 5 : detect the data types of all columns in df_selected.pkl
# this function loads the selected dataframe, identifies numerical,
# categorical and datetime columns, saves the result to column_types.csv,
# and returns a dictionary with the detected column groups
types_dict = detect_types()

# display the dictionary with column type groups
types_dict

saved: /content/drive/MyDrive/ml_project/column_types.csv
{'numerical': ['Quantity', 'Unit_Price'], 'categorical': ['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category', 'Order_Status'], 'datetime': []}

{'numerical': ['Quantity', 'Unit_Price'],
 'categorical': ['PO_ID',
  'Supplier',
  'Order_Date',
  'Delivery_Date',
  'Item_Category',
  'Order_Status'],
 'datetime': []}

In [7]:
# step 6: show ui for selecting the date column and the fill method
# the function displays a widget where the user chooses:
# - which column contains dates
# - how missing values should be filled (zero, ffill, mean)
# the choices are saved to date_settings.txt

set_date_ui()

VBox(children=(Label(value='select the date column:'), Dropdown(options=('PO_ID', 'Supplier', 'Order_Date', 'D…

In [8]:
# step 7: apply the date settings selected in the ui
# this function:
# - loads df_selected.pkl from drive
# - reads the date column and fill method from date_settings.txt
# - converts the date column to datetime
# - sorts the dataframe by date
# - fills missing values using the chosen method
# - saves the result as df_date.pkl
# - returns the processed dataframe for preview

df_date = set_date()
df_date.head()

saved: /content/drive/MyDrive/ml_project/df_date.pkl

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price
558,PO-00559,Alpha_Inc,2022-01-01,2022-01-07,Raw Materials,Delivered,1042,36.74
179,PO-00180,Alpha_Inc,2022-01-01,2022-01-12,Electronics,Delivered,552,21.52
521,PO-00522,Delta_Logistics,2022-01-02,2022-01-06,Packaging,Delivered,85,22.54
302,PO-00303,Alpha_Inc,2022-01-03,2022-01-20,Packaging,Delivered,172,63.61
420,PO-00421,Alpha_Inc,2022-01-04,2022-01-06,Electronics,Delivered,1004,50.70

In [9]:
# step 8: ui that loads df_date.pkl from drive,
# counts missing values in the dataframe,
# shows the number of missing values,
# and lets the user choose how to handle them:
# drop, zero, ffill, mean or none.
from clean_data import clean_data_ui
clean_data_ui()

VBox(children=(Label(value='PO_ID: 0 missing'), Label(value='Supplier: 0 missing'), Label(value='Order_Date: 0…

In [10]:
# step 9: applies the cleaning method selected in step 8.
# loads df_date.pkl and clean_method.txt from drive,
# performs: drop rows, fill with zero, forward fill,
# fill with mean or leave unchanged,
# then saves the result to df_clean.pkl.
df_clean = clean_data()
df_clean.head()

saved: /content/drive/MyDrive/ml_project/df_clean.pkl
applied per-column cleaning methods

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price
558,PO-00559,Alpha_Inc,2022-01-01,2022-01-07,Raw Materials,Delivered,1042,36.74
179,PO-00180,Alpha_Inc,2022-01-01,2022-01-12,Electronics,Delivered,552,21.52
521,PO-00522,Delta_Logistics,2022-01-02,2022-01-06,Packaging,Delivered,85,22.54
302,PO-00303,Alpha_Inc,2022-01-03,2022-01-20,Packaging,Delivered,172,63.61
420,PO-00421,Alpha_Inc,2022-01-04,2022-01-06,Electronics,Delivered,1004,50.70

In [11]:
# step 10: date column selection for calendar features
date_features_ui()

VBox(children=(Label(value='select the date column for feature generation:'), Dropdown(options=('PO_ID', 'Supp…

In [12]:
# step 11: generate calendar features
df_date_features = date_features()
df_date_features.head()

saved: /content/drive/MyDrive/ml_project/df_date_features.pkl

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,year,month,day,dayofweek
558,PO-00559,Alpha_Inc,2022-01-01,2022-01-07,Raw Materials,Delivered,1042,36.74,2022,1,1,5
179,PO-00180,Alpha_Inc,2022-01-01,2022-01-12,Electronics,Delivered,552,21.52,2022,1,1,5
521,PO-00522,Delta_Logistics,2022-01-02,2022-01-06,Packaging,Delivered,85,22.54,2022,1,2,6
302,PO-00303,Alpha_Inc,2022-01-03,2022-01-20,Packaging,Delivered,172,63.61,2022,1,3,0
420,PO-00421,Alpha_Inc,2022-01-04,2022-01-06,Electronics,Delivered,1004,50.70,2022,1,4,1

In [ ]:
# step 12: user interface for lag configuration
# in this step the system loads the dataframe created after date feature generation (df_date_features.pkl)
# all column names are displayed in a dropdown widget
# the user selects one specific column for which lag features will be generated (for example sales or demand_qty)
# an additional text field allows the user to enter multiple lag periods separated by commas, such as: 1,2,7,14
# these lag settings are saved into a text file (lags_method.txt) so the next processing step can read the user choices
create_lags_ui()

In [ ]:
# step 13: lag feature generation based on user selections
# in this step the system reads the saved user selections from lags_method.txt (selected column + list of lag values)
# the system loads the dataframe again (df_date_features.pkl)
# for each lag value provided by the user, the system creates a new column in the dataframe
# example: if the user selected column 'sales' and lag values '1,2,7', the system creates:
#   sales_lag_1  = sales shifted by 1 period
#   sales_lag_2  = sales shifted by 2 periods
#   sales_lag_7  = sales shifted by 7 periods
# shifting means that each new column contains the value of the original column from previous rows
# this allows time-series models to use past values as input features
# after creating all lag columns, the final dataframe is saved as df_lags.pkl for the next steps of your pipeline
create_lags()

In [ ]:
# step 14: user selects the categorical columns to encode and chooses the encoding method (ui)
# in this step the system loads the dataframe produced after generating lag features (df_lags.pkl)
# the interface scans the dataframe and automatically detects which columns are of type object/string
# only these columns appear in the selection list, because only text-based columns can be encoded
# the user selects one or more categorical columns that require encoding
# the interface also provides a dropdown for choosing the encoding method:
#   onehot – creates separate 0/1 indicator columns for every unique category value
#   mean – replaces each category with the mean of the target variable calculated for that category
# after the user confirms the selection, both the chosen columns and the selected method
# are saved into a configuration file (encode_method.txt)
encode_categories_ui()

In [ ]:
# step 15: encode selected categorical features according to the chosen method (processing)
# in this step the system reads the user's choices from encode_method.txt
# the system loads the dataframe again (df_lags.pkl) to ensure that encoding is performed on the full dataset
# when method is "onehot":
#   the system uses pandas.get_dummies() to create new binary columns, one column per category
#   for example, if a column 'color' has values 'red', 'blue', 'green',
#   the system generates: color_red, color_blue, color_green
#   original column is removed and replaced with these indicator columns
# when method is "mean":
#   each selected column is replaced by a numerical value representing the mean of the target variable
#   for each category, the system computes: mean(target | category)
#   then replaces the category string with this mean value
#   this approach is useful in models where too many dummy variables cause performance issues
# finally, the fully encoded dataframe is saved as df_encoded.pkl in the project directory
encode_categories()